/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.util.ArrayList;
import java.util.List;
import entidades.Equipe;
import entidades.Jogador;
import entidades.Jogo;
import persistência.EquipeDAO;

/**
 *
 * @author diego.freitas
 */
public class FrmEscolherTime extends javax.swing.JFrame {

    /**
     * Creates new form FrmEscolherTime
     */
    List<Equipe> equipes = new ArrayList<Equipe>();
    Equipe mandante, visitante;
    public FrmEscolherTime() {
        initComponents();
        EquipeDAO dao = new EquipeDAO();
        
        equipes = dao.listarTodos();
        
        for(Equipe equipe : equipes){
            cmbEscolherTime.addItem(equipe.getNome());
            cmbEscolherAdv.addItem(equipe.getNome());
        }
        
        cmbEscolherTime.setSelectedIndex(0);
        cmbEscolherAdv.setSelectedIndex(1);
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbEscolherTime = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        OkJogador = new javax.swing.JButton();
        cmbEscolherAdv = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        OkAdversario = new javax.swing.JButton();
        btnSeguir = new javax.swing.JButton();
        lblJogador1 = new javax.swing.JLabel();
        lblJogador2 = new javax.swing.JLabel();
        lblJogador3 = new javax.swing.JLabel();
        lblAdversario1 = new javax.swing.JLabel();
        lblAdversario2 = new javax.swing.JLabel();
        lblAdversario3 = new javax.swing.JLabel();
        prgJogador1 = new javax.swing.JProgressBar();
        prgJogador2 = new javax.swing.JProgressBar();
        prgJogador3 = new javax.swing.JProgressBar();
        prgAdversario1 = new javax.swing.JProgressBar();
        prgAdversario3 = new javax.swing.JProgressBar();
        prgAdversario2 = new javax.swing.JProgressBar();
        prgEntrosamento1 = new javax.swing.JProgressBar();
        prgEntrosamento2 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N

        cmbEscolherTime.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        cmbEscolherTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEscolherTimeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel1.setText("Escolha o time");

        OkJogador.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        OkJogador.setText("Ok");
        OkJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkJogadorActionPerformed(evt);
            }
        });

        cmbEscolherAdv.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        cmbEscolherAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEscolherAdvActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel2.setText("Escolha o Adversário");

        OkAdversario.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        OkAdversario.setText("Ok");
        OkAdversario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkAdversarioActionPerformed(evt);
            }
        });

        btnSeguir.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        btnSeguir.setText("Seguir");
        btnSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguirActionPerformed(evt);
            }
        });

        lblJogador1.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        lblJogador1.setText("jLabel3");

        lblJogador2.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        lblJogador2.setText("jLabel4");

        lblJogador3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        lblJogador3.setText("jLabel5");

        lblAdversario1.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        lblAdversario1.setText("jLabel3");

        lblAdversario2.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        lblAdversario2.setText("jLabel4");

        lblAdversario3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        lblAdversario3.setText("jLabel5");

        prgJogador1.setMaximum(10);

        prgJogador2.setMaximum(10);

        prgJogador3.setMaximum(10);

        prgAdversario1.setMaximum(10);

        prgAdversario3.setMaximum(10);

        prgAdversario2.setMaximum(10);

        prgEntrosamento1.setMaximum(10);

        prgEntrosamento2.setMaximum(10);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel3.setText("Entrosamento");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel4.setText("Entrosamento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbEscolherTime, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblJogador2)
                                            .addComponent(lblJogador3)
                                            .addComponent(lblJogador1)
                                            .addComponent(jLabel4))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(prgJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(prgJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(prgJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(prgEntrosamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jLabel1)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(cmbEscolherAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(prgEntrosamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAdversario3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(prgAdversario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAdversario2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(prgAdversario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAdversario1)
                                            .addGap(91, 91, 91)
                                            .addComponent(prgAdversario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(59, 59, 59))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(OkJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OkAdversario, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSeguir)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEscolherTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJogador1)
                            .addComponent(prgJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prgJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJogador2))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJogador3)
                            .addComponent(prgJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prgEntrosamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEscolherAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAdversario1)
                                    .addComponent(prgAdversario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prgAdversario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAdversario2))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prgAdversario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAdversario3))
                                .addGap(37, 37, 37)
                                .addComponent(prgEntrosamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OkJogador)
                    .addComponent(OkAdversario))
                .addGap(18, 18, 18)
                .addComponent(btnSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrmPreJogo form = new FrmPreJogo(mandante, visitante);
        form.pack();
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_btnSeguirActionPerformed

    private void cmbEscolherTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEscolherTimeActionPerformed
        // TODO add your handling code here:
       for(Equipe equipe : equipes){
           if(equipe.getNome().equals(cmbEscolherTime.getSelectedItem())){
               lblJogador1.setText(equipe.getJogadores().get(0).getNome());
               prgJogador1.setValue(equipe.getJogadores().get(0).getOverall());
               lblJogador2.setText(equipe.getJogadores().get(1).getNome());
               prgJogador2.setValue(equipe.getJogadores().get(1).getOverall());
               lblJogador3.setText(equipe.getJogadores().get(2).getNome());
               prgJogador3.setValue(equipe.getJogadores().get(2).getOverall());
               prgEntrosamento1.setValue((int) equipe.getEntrosamento());
           }
       }
       
       
        
    }//GEN-LAST:event_cmbEscolherTimeActionPerformed

    private void cmbEscolherAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEscolherAdvActionPerformed
        // TODO add your handling code here:
        
        for(Equipe equipe : equipes){
           if(equipe.getNome().equals(cmbEscolherAdv.getSelectedItem())){
               lblAdversario1.setText(equipe.getJogadores().get(0).getNome());
               prgAdversario1.setValue(equipe.getJogadores().get(0).getOverall());
               lblAdversario2.setText(equipe.getJogadores().get(1).getNome());
               prgAdversario2.setValue(equipe.getJogadores().get(1).getOverall());
               lblAdversario3.setText(equipe.getJogadores().get(2).getNome());
               prgAdversario3.setValue(equipe.getJogadores().get(2).getOverall());
               prgEntrosamento2.setValue((int) equipe.getEntrosamento());
           }
       }
    }//GEN-LAST:event_cmbEscolherAdvActionPerformed

    private void OkJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkJogadorActionPerformed
        // TODO add your handling code here:
        
        for(Equipe equipe : equipes){
           if(equipe.getNome().equals(cmbEscolherTime.getSelectedItem())){
               mandante = equipe;
           }
        }  
        
        equipes.remove(mandante);
        cmbEscolherTime.setEnabled(false);
        OkJogador.setEnabled(false);

        if(OkAdversario.isEnabled()){
             cmbEscolherAdv.removeAllItems();

             for(Equipe equipe : equipes){
                 cmbEscolherAdv.addItem(equipe.getNome());
             }
        }else{
            btnSeguir.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_OkJogadorActionPerformed

    private void OkAdversarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkAdversarioActionPerformed
        // TODO add your handling code here:
        for(Equipe equipe : equipes){
           if(equipe.getNome().equals(cmbEscolherAdv.getSelectedItem())){
               visitante = equipe;
           }
        }
        
        equipes.remove(visitante);
        cmbEscolherAdv.setEnabled(false);
        OkAdversario.setEnabled(false);

        if(OkJogador.isEnabled()){
             cmbEscolherTime.removeAllItems();

             for(Equipe equipe : equipes){
                 cmbEscolherTime.addItem(equipe.getNome());
             }
        }else{
            btnSeguir.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_OkAdversarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEscolherTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEscolherTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEscolherTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEscolherTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEscolherTime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkAdversario;
    private javax.swing.JButton OkJogador;
    private javax.swing.JButton btnSeguir;
    private javax.swing.JComboBox<String> cmbEscolherAdv;
    private javax.swing.JComboBox<String> cmbEscolherTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAdversario1;
    private javax.swing.JLabel lblAdversario2;
    private javax.swing.JLabel lblAdversario3;
    private javax.swing.JLabel lblJogador1;
    private javax.swing.JLabel lblJogador2;
    private javax.swing.JLabel lblJogador3;
    private javax.swing.JProgressBar prgAdversario1;
    private javax.swing.JProgressBar prgAdversario2;
    private javax.swing.JProgressBar prgAdversario3;
    private javax.swing.JProgressBar prgEntrosamento1;
    private javax.swing.JProgressBar prgEntrosamento2;
    private javax.swing.JProgressBar prgJogador1;
    private javax.swing.JProgressBar prgJogador2;
    private javax.swing.JProgressBar prgJogador3;
    // End of variables declaration//GEN-END:variables
}
